# Generated by Django 3.0 on 2021-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_cart', models.CharField(default=None, max_length=100)),
                ('p_cart_uid', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
