# Generated by Django 3.2.12 on 2022-04-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_organ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='admin', max_length=100)),
                ('Password', models.CharField(default='admin', max_length=100)),
            ],
            options={
                'db_table': 'Admin_Details',
            },
        ),
        migrations.CreateModel(
            name='organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(default=None, max_length=100)),
                ('donor_age', models.CharField(default=None, max_length=100)),
                ('donor_BG', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('location', models.CharField(default=None, max_length=100)),
                ('price', models.CharField(default=None, max_length=100)),
                ('stat', models.CharField(default='unbooked', max_length=100)),
            ],
            options={
                'db_table': 'Organ_details',
            },
        ),
        migrations.CreateModel(
            name='requests_made',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default=None, max_length=100)),
                ('thing', models.CharField(default=None, max_length=100)),
                ('status', models.CharField(default=None, max_length=100)),
                ('Image1', models.ImageField(default=None, upload_to='Files')),
                ('video', models.FileField(blank=True, null=True, upload_to='Files')),
                ('vid_id', models.IntegerField(default=0, max_length=100)),
            ],
            options={
                'db_table': 'Request_made_Details',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('year', models.CharField(default=None, max_length=100)),
                ('sem', models.CharField(default=None, max_length=100)),
                ('internship', models.CharField(default=None, max_length=100)),
                ('project', models.CharField(default=None, max_length=100)),
                ('branch', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
                ('Adhar', models.IntegerField(default=None, max_length=12)),
                ('Image1', models.ImageField(upload_to='Files')),
                ('video', models.ImageField(default=None, upload_to='Files')),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
        migrations.DeleteModel(
            name='product_cart',
        ),
    ]
