# Generated by Django 3.2.12 on 2022-04-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_organ', '0002_auto_20220417_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Adhar',
            field=models.IntegerField(default=None, max_length=100),
        ),
    ]
